apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: simple-test1
  labels:
    dast.scan: "true"
spec:
  rules:
  - host: 12.foo.com
    http:
      paths:
      - backend:
          service:
            name: svc1
            port:
              number: 8080
        path: /bar
        pathType: Exact
status:
  loadBalancer: {}
